services:
  api:
    build: .
    ports:
      - '3007:3007'
    depends_on:
      - notification_db
    environment:
      DB_HOST: notification_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: notificationdb
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672
    networks:
      - app-network

  notification_db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notificationdb
    ports:
      - '5435:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    external: true

volumes:
  postgres-data:
